# Install script for directory: /Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/HelloWorld/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/MultiThreadedDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/OpenCLClothDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/OpenGL/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/AllBulletDemos/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/CcdPhysicsDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/BulletXmlImportDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConstraintDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/SliderConstraintDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/GenericJointDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/Raytracer/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/RagdollDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ForkLiftDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/BasicDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/RollingFrictionDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/RaytestDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/VoronoiFractureDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/GyroscopicDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/FractureDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/Box2dDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/BspDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/MovingConcaveDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/VehicleDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/CharacterDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/SoftDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/SimplexDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/DynamicControlDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConvexHullDistance/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/DoublePrecisionDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConcaveDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/CollisionDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ContinuousConvexCollision/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/GjkConvexCastDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/MultiMaterialDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/SerializeDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/InternalEdgeDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/Benchmarks/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/ThreadingDemo/cmake_install.cmake")
  INCLUDE("/Users/kristofe/Documents/Projects/GameEngine/SupportLibraries/bullet-2.82/Demos/VectorAdd_OpenCL/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

