/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blackicegamesnyc_GameEngine_GameEngineRenderer */

#ifndef _Included_com_blackicegamesnyc_GameEngine_GameEngineRenderer
#define _Included_com_blackicegamesnyc_GameEngine_GameEngineRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blackicegamesnyc_GameEngine_GameEngineRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blackicegamesnyc_GameEngine_GameEngineRenderer_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_blackicegamesnyc_GameEngine_GameEngineRenderer
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_blackicegamesnyc_GameEngine_GameEngineRenderer_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_blackicegamesnyc_GameEngine_GameEngineRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blackicegamesnyc_GameEngine_GameEngineRenderer_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_blackicegamesnyc_GameEngine_GameEngineGLSurface
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blackicegamesnyc_GameEngine_GameEngineGLSurface_nativePause
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
